//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.PDFRedaction.Activities.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiPathTeam_PDFRedaction_Activities_Design {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPathTeam_PDFRedaction_Activities_Design() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.PDFRedaction.Activities.Design.Properties.UiPathTeam.PDFRedaction.Acti" +
                            "vities.Design", typeof(UiPathTeam_PDFRedaction_Activities_Design).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to view.
        /// </summary>
        public static string DoubleClickToView {
            get {
                return ResourceManager.GetString("DoubleClickToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileInput.
        /// </summary>
        public static string FileInput {
            get {
                return ResourceManager.GetString("FileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input File.  Relative Paths are not allowed.  Please provide a fully rooted path to the input file..
        /// </summary>
        public static string FileInputHint {
            get {
                return ResourceManager.GetString("FileInputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileOutput.
        /// </summary>
        public static string FileOutput {
            get {
                return ResourceManager.GetString("FileOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouptut PDF File.  Relative Paths are not allowed.  Please provide a fully rooted path to the output file..
        /// </summary>
        public static string FileOutputHint {
            get {
                return ResourceManager.GetString("FileOutputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormulaAuto.
        /// </summary>
        public static string FormulaAuto {
            get {
                return ResourceManager.GetString("FormulaAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of prebuilt regex patterns.  Specify which regex patters to apply in the redaction.  Here are the available options.\r\n{\&quot;ssn\&quot;,\&quot;phone\&quot;,\&quot;email\&quot;,\&quot;dates\&quot;,\&quot;ein\&quot;,\&quot;phone\&quot;,\&quot;currency\&quot;}.
        /// </summary>
        public static string FormulaAutoHint {
            get {
                return ResourceManager.GetString("FormulaAutoHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Custom Regex Patterns to use in the redaction.
        /// </summary>
        public static string FormulaHint {
            get {
                return ResourceManager.GetString("FormulaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop OCR Engine Activity Here.
        /// </summary>
        public static string OCREngineContainerHint {
            get {
                return ResourceManager.GetString("OCREngineContainerHint", resourceCulture);
            }
        }
    }
}
